name: 'magicpod-datadog-action'
description: 'Send metrics of MagicPod to Datadog'
inputs:
  dd_api_token:
    description: 'Datadog API Token'
    required: true
  magicpod_api_token:
    description: 'MagicPod API Token'
    required: true
  magicpod_organization_name:
    description: 'MagicPod Organization Name'
    required: true
  magicpod_project_name:
    description: 'MagicPod Organization Name'
    required: true
  magicpod_record_count:
    description: 'MagicPod recort count to retrive BatchRun'
    required: false
    default: '20'
runs:
  using: 'node16'
  main: 'dist/index.js'
